name: user_repository
description: A starting point for Dart libraries or applications.
publish_to: none

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  shared_preferences: ^2.1.0
  flutter_riverpod: ^2.3.2
  riverpod_annotation: ^2.0.2
  petfinder_api:
    path: ../petfinder_api
  domain_models:
    path: ../domain_models

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  riverpod_generator: ^2.1.4
