name: domain_models
description: A starting point for Dart libraries or applications.
publish_to: none

environment:
  sdk: '>=2.19.3 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  freezed_annotation: ^2.2.0
