name: routing
description: A starting point for Dart libraries or applications.
publish_to: 'none'

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^6.5.9
  go_router_builder: ^1.2.2
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  user_repository:
    path: ../user_repository
  onboarding:
    path: ../features/onboarding
  animals_near_you:
    path: ../features/animals_near_you
  search:
    path: ../features/search

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  riverpod_generator: ^2.2.1
  build_runner: ^2.3.3
  lints: ^2.0.0
  test: ^1.21.0
