name: search
description: A starting point for Dart libraries or applications.
publish_to: 'none'

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  go_router: ^6.5.9
  infinite_scroll_pagination: ^4.0.0-dev.1
  geolocator: ^9.0.2
  freezed_annotation: ^2.2.0
  rxdart: ^0.27.7
  domain_models:
    path: ../../../packages/domain_models
  animal_repository:
    path: ../../../packages/animal_repository
  animals_near_you:
    path: ../../../packages/features/animals_near_you
  routing:
    path: ../../../packages/routing

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.21.0
  flutter_lints: ^1.0.4
  riverpod_generator: ^2.2.1
  build_runner: ^2.3.3
  freezed: ^2.3.2

flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/