name: animal_repository
description: A starting point for Dart libraries or applications.
publish_to: none

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  petfinder_api:
    path: ../petfinder_api
  local_storage:
    path: ../local_storage
  domain_models:
    path: ../domain_models
  flutter_riverpod: ^2.3.2
  riverpod_annotation: ^2.0.2
  path_provider: ^2.0.14

dev_dependencies:
  riverpod_generator: ^2.1.4
  build_runner: ^2.3.3
  lints: ^2.0.0
  test: ^1.21.0
