name: onboarding
description: A starting point for Dart libraries or applications.
publish_to: 'none'

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  carousel_slider: ^4.2.1
  go_router: ^6.5.9
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  flutter:
    sdk: flutter
  user_repository:
    path: ../../../packages/user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.21.0
  flutter_lints: ^1.0.4
  riverpod_generator: ^2.2.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/