name: onboarding
description: A starting point for Dart libraries or applications.
publish_to: 'none'

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.21.0
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/