name: petfinder_api
description: A starting point for Dart libraries or applications.
publish_to: none

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  dio: ^5.1.1
  json_annotation: ^4.8.0
  retrofit: ^4.0.1
  shared_preferences: ^2.1.0
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1

dev_dependencies:
  mockito: ^5.4.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  lints: ^2.0.1
  test: ^1.24.2
  retrofit_generator: ^6.0.0+3
  riverpod_generator: ^2.2.1