name: animals_near_you
description: A starting point for Dart libraries or applications.
publish_to: 'none'

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.2
  riverpod_annotation: ^2.0.2
  go_router: ^6.2.0
  infinite_scroll_pagination: ^4.0.0-dev.1
  domain_models:
    path: ../../../packages/domain_models
  animal_repository:
    path: ../../../packages/animal_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.21.0
  flutter_lints: ^1.0.4
  riverpod_generator: ^2.1.4
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/