name: local_storage
description: A starting point for Dart libraries or applications.
publish_to: none

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  isar_generator: ^3.1.0+1
  path_provider: ^2.0.14
  riverpod_annotation: ^2.1.1
  riverpod_generator: ^2.2.1
  domain_models:
    path: ../domain_models
  animal_repository:
    path: ../animal_repository

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
