name: local_storage
description: A starting point for Dart libraries or applications.
publish_to: none

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  path_provider: ^2.0.14
  
dev_dependencies:
  riverpod_generator: ^2.2.1
  build_runner: ^2.3.3
  isar_generator: ^3.1.0+1
  lints: ^2.0.1
  test: ^1.24.2
