name: local_storage
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  flutter_riverpod: ^2.3.2
  riverpod_annotation: ^2.0.2
  path_provider: ^2.0.14
dev_dependencies:
  riverpod_generator: ^2.1.4
  build_runner: ^2.3.3
  isar_generator: ^3.0.5
  lints: ^2.0.0
  test: ^1.21.0
